routes/web.php
<?php

use App\Http\Controllers\TasksController;
use Illuminate\Support\Facades\Route;
use App\Task;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin/welcome');
// });
// Route::get('/', function () {
//     return view
// }


Route::resource('team', 'TeamsController')->middleware('auth');
Route::resource('task', 'TasksController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');

Route::get('task/{task}/assign', 'TasksController@assign')->name('task.assign');
Auth::routes();
Route::get('task/show/{status}', 'TasksController@memberTasks')->name('task.membertasks');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', function () {

    // if (auth()->user()) {

    //     $user = auth()->user();
    //     if ($user->isLeader()) {
    //         $tasks = Task::where('team_id', $user->team_id)->get();
    //         return view('leaderDashboard')->with(['tasks' => $tasks]);
    //     }
    //     if ($user->isMember()) {
    //         $taskIds = DB::table('users_tasks')->where('user_id', 9)->pluck('task_id');
    //         $tasks = Task::whereIn('id', $taskIds)->get();
    //         return view('memberDashboard')->with(['tasks' => $tasks]);
    //     }
    // } else {
    //     return redirect(route('login'));
    // }
})->name('dashboard')->middleware('roleForDashboard');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Task extends Model
{
    protected $fillable = ['title', 'deadline', 'priority'];
    protected $dates = ['deadline'];

    public function team()
    {
        return $this->belongsTo(Team::class);
    }
    public function users()
    {
        return $this->belongsToMany(User::class, 'users_tasks', 'task_id', 'user_id')->withPivot('status', 'points');;
    }
    public function assignedTo()
    {

        return $this->users()->wherePivot('status', 'assigned')->first();
        // return DB::table('users_tasks')->where('task_id', $this->id)->where('status', 'assigned')->pluck('user_id')->first();
    }
    /**
     * ACCESSORS
     */

    public function makeLabel($color, $text)
    {
        return '<div class="d-flex ' . $color . ' justify-content-center align-items-center"><p class=" p-0 m-0  text-white">' .  $text . '</p></div>';
    }
    public function getPriorityAttribute($value)
    {

        if ($value === 2) {
            return $this->makeLabel('bg-danger', 'HIGH');
        }
        if ($value === 1) {
            return $this->makeLabel('bg-warning', 'MEDIUM');
        }
        if ($value === 0) {
            return $this->makeLabel('bg-primary', 'LOW');
        }
    }

    //helper classes

    public function status()
    {

        if (auth()->user()->role === 'team-member') {

            $status = $auth->user()->tasks()->where('task_id', $this->id)->first()->status;
            return $status;
        }

        if (auth()->user()->isLeader()) {
            if ($this->status === 'completed') {
                return 'completed';
            }

            if ($this->deadline < now()) {
                return 'failed';
            }
        }





        return $this->status;
    }

    public function statusColor()
    {

        $statusText = "text-secondary";

        if ($this->status === 'completed') {
            return 'text-success';
        }

        if ($this->status === 'failed') {
            return 'text-danger';
        }

        if ($this->status === 'assigned') {
            return "text-primary";
        }

        return $statusText;
    }


    public static function updateFailedTasks()
    {

        //tasks ids of the tasks whose status is 'assigned' or 'review'
        $tasksForCheck =   DB::table('users_tasks')
            ->whereNotIn('status', ['failed', 'completed'])
            ->pluck('task_id');

        $failedTasksIds = DB::table('tasks')
            ->whereIn('id', $tasksForCheck)
            ->where('deadline', '<', now())
            ->pluck('id');

        DB::table('users_tasks')
            ->whereIn('task_id', $failedTasksIds)
            ->update(['status' => 'failed']);


        $failedMembers =  DB::table('users_tasks')
            ->whereIn('task_id', $failedTasksIds)
            ->pluck('user_id');

        DB::table('users')
            ->whereIn('id', $failedMembers)
            ->increment('points', -5);

        DB::table('tasks')
            ->whereNotIn('status', ['completed', 'failed'])
            ->where('deadline', '<', now())
            ->update(['status' => 'failed']);
    }

    public function updateRecordStatus($memberId, $status)
    {
        DB::table('users_tasks')->where([['task_id', '=', $this->id], ['user_id', '=', $memberId]])->update(['status' => $status]);
    }
    public function updateRecordPoints($memberId, $points)
    {
        DB::table('users_tasks')->where([['task_id', '=', $this->id], ['user_id', '=', $memberId]])->update(['points' => $points]);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\Team;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TasksController extends Controller
{


    public function __construct()
    {
        $this->middleware('updateRecords')->only(['update', 'memberTasks']);
    }

    public function index()
    {
        $this->authorize('viewAny', new Task());
        return view('task.index')
            ->with(['tasks' => auth()->user()->team->tasks, 'team' => auth()->user()->team]);
    }

    public function memberTasks($status)
    {

        $member = auth()->user();

        if ($status === 'completed')
            return view('task.member.index')
                ->with(['tasks' => $member->completedTasks()]);

        if ($status === 'assigned')
            return view('task.member.index')
                ->with(['tasks' => $member->assignedTasks()]);

        if ($status === 'review')
            return view('task.member.index')
                ->with(['tasks' => $member->underReviewTasks()]);

        if ($status === 'failed')
            return view('task.member.index')
                ->with(['tasks' => $member->failedTasks()]);
    }

    public function create()
    {
        return view('task.create')
            ->with(['members' => auth()->user()->team->members]);
    }

    public function store(Request $request)
    {

        //setting title,priority and deadline with mass assignment
        $task = new Task(request()->all());


        $team = auth()->user()->team;
        $task->team_id = $team->id;
        $task->status = "created";
        // $task->save();


        if (request('is-automatic') === 'true') {

            //if priority of the task is highest then task should be assigned to only best member


            //check whether any vacant user exists and if exists more than 1
            // then the task will be assigned to the user which has highest points
            $member = $team->members()->where('assigned_tasks', 0)->orderByDesc('points')->orderByDesc('total_login_time')->first();

            if ($member) {

                dd($member->id);
                //assign the task to that member that is best in vacant

            } else {
                $member = User::all()->orderByDesc('points')->orderByDesc('total_login_time')->orderBydesc('assigned_tasks')->first();
                dd($member->Id);
                //no vacant user is found
                //assing the task to the user who has less no of assigned tasks



            }


            //if no vacant user is available
            //assign the task the user who has less numbers of tasks


        }

        $memberId = request('member');
        $member = User::find($memberId);
        $task->status = "assigned";
        $task->save();
        $member->tasks()->attach([$task->id], ['status' => 'assigned']);
        $member->updateAssignedCount(1);
        return redirect(route('task.index'));
    }

    public function edit(Task $task)
    {
        return view('task.create')
            ->with(['members' => auth()->user()->team->members]);
    }

    public function assign(Task $task)
    {
        return view('task.assign')
            ->with([
                'task' => $task,
                'members' => auth()->user()->team->members
            ]);
    }


    public function update(Request $request, Task $task)
    {


        if (request('is_task_assign'))
            return $this->assignTask($task);

        if (request('is_task_submit'))
            return $this->submitTask($task);

        if (request('is_task_giveup'))
            return $this->giveUpTask($task);

        if (request('is_task_accept'))
            return $this->acceptTask($task);

        if (request('is_task_reassign'))
            return $this->reAssignTask($task);
    }




    /****************************HELPER FUNCTIONS********************************** */

    private function assignTask($task)
    {
        $task->priority = request('task-priority');
        $task->deadline = request('task-deadline');
        $task->status = "created";
        $task->save();
        $memberId = request('task-member');
        $member = User::find($memberId);
        $member->updateAssignedCount(1);
        $alreadyExistRecord = $member->task($task->id)->first();
        if ($alreadyExistRecord) {

            //record already exists in users_tasks of user with this task
            // we donot need to create new record
            // we only have to update the status

            $task->updateRecordStatus($memberId, 'assigned');
        } else {

            $member->tasks()->attach([$task->id], ['status' => 'assigned']);
        }
        $task->status = "assigned";
        $task->save();
        return redirect(route('dashboard'));
    }


    private function submitTask($task)
    {
        $task->status = "review";
        $task->save();
        $memberId = request('task_member');
        $member = User::find($memberId);
        $member->updateAssignedCount(-1);
        $task->updateRecordStatus($memberId, 'review');
        return redirect(route('dashboard'));
    }

    private function giveUpTask($task)
    {
        $task->status = "created";
        $task->save();
        $memberId = request('task_member');
        $member = User::find($memberId);
        $member->updateAssignedCount(-1);
        $member->updatePoints(-3);
        $task->updateRecordStatus($memberId, 'failed');
        return redirect(route('dashboard'));
    }

    private function acceptTask($task)
    {

        $task->status = "completed";
        $task->save();
        $memberId = DB::table('users_tasks')
            ->where('task_id', $task->id)
            ->where('status', 'review')
            ->pluck('user_id')
            ->first();
        $member = User::find($memberId);
        $points = request('task_points');
        $member->updatePoints($points);
        $task->updateRecordStatus($memberId, 'completed');
        $task->updateRecordPoints($memberId, $points);
        $task->save();
        return redirect(route('dashboard'));
    }

    private function reAssignTask($task)
    {
        $task->status = "assigned";
        $task->save();
        $memberId = DB::table('users_tasks')
            ->where('task_id', $task->id)
            ->where('status', 'review')
            ->pluck('user_id');
        $member = User::find($memberId)->first();
        $member->updateAssignedCount(+1);
        $member->updatePoints(-1);
        $task->updateRecordStatus($memberId, 'assigned');
        return redirect(route('dashboard'));
    }
}

resources/views/task/assign.blade.php
@extends('layouts.app')
@section('page-title','Create Task')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection
@section('content')


<div class="row">
    <div class="mx-auto col-md-8">

    <form action="{{ route('task.update',$task) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Task Title</label>
              <input
                type="text"
                name="task-title"
                class="form-control"
                value="{{$task->title}}"
                disabled
                placeholder="title">
        </div>

        <div class="form-group">
            <label for="task-deadline">Task Deadline</label>
            <input type="date"
            class="form-control"
            name="task-deadline"
            placeholder="Click here to enter a deadline"
            id="task-deadline">

        </div>


        <div class="form-group">
            <label for="sel1">Select Severity</label>
            <select class="form-control" name="task-priority">
                {{-- <option disabled selected value> -- Select an Severity -- </option> --}}
                <option value=0 @if($task->priority === 0)  selected @endif>Medium</option>
                <option value=1 @if($task->priority === 1)  selected @endif>High</option>
                <option value=2 @if($task->priority === 2)  selected @endif>Highest</option>
            </select>
        </div>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2 mb-2" role="group" aria-label="First group">
              <button type="button" id="chooseButton" onclick="chooseButtonClicked()" class="btn btn-secondary">Choose Member Manually</button>

            </div>
            <div class="btn-group mr-2 mb-2" role="group" aria-label="Second group">
              <button type="button" onclick="automaticButtonClicked()" class="btn btn-secondary">Assign Task Automatically</button>

            </div>
        </div>

        <input type="hidden" id="is-automatic" name="is-automatic" value="false">

        <div class="form-group" id="choose-member">
            <label for="sel1">Select Member</label>
            <select class="form-control" name="task-member">
                <option disabled selected value> -- Select an Member-- </option>
                @foreach($members as $member)
                    @if(!$member->isLeader())
                      <option value="{{$member->id}}">{{$member->name}}</option>
                    @endif
                  @endforeach
            </select>
        </div>


        <input type="hidden" name="is_task_assign" value="true">

        <button type="submit" class="btn btn-primary">Assign</button>
    </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    var taskDeadline = @json($task->deadline->toDateTimeString());

      flatpickr("#task-deadline", {
            enableTime: true,
            minDate: 'today',
            allowInput: true,
            dateFormat: "Y-m-d H:i:ss",
            defaultDate: taskDeadline,

        });

        $chooseMemberSelect = document.getElementById('choose-member');
        $isAutomatic = document.getElementById('is-automatic');
        document.getElementById('chooseButton').click();

        function chooseButtonClicked()
        {
            console.log("jdbjd");
            $isAutomatic.value = "false";
            $chooseMemberSelect.classList.remove('d-none');
        }
        function automaticButtonClicked()
        {

            $isAutomatic.value = "true";
            console.log($isAutomatic);
            $chooseMemberSelect.classList.add('d-none');
        }

</script>

@endsection

resources/views/task/create.blade.php
@extends('layouts.app')
@section('page-title','Create Task')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection
@section('content')


<div class="row">
    <div class="mx-auto col-md-8">
    <form action="{{ route('task.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Task Title</label>
              <input type="text" name="title" class="form-control"  placeholder="title">
        </div>

        <div class="form-group">
            <label for="task-deadline">Task Deadline</label>
            <input type="date"
            class="form-control"
            name="deadline"
            placeholder="Click here to enter a deadline"
            id="task-deadline">
        </div>


        <div class="form-group">
            <label for="sel1">Select Severity</label>
            <select class="form-control" name="priority">
                <option disabled selected value> -- Select an Severity -- </option>
                <option value=0>Medium</option>
                <option value=1>High</option>
                <option value=2>Highest</option>
            </select>
        </div>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2 mb-2" role="group" aria-label="First group">
              <button type="button" id="chooseButton" onclick="chooseButtonClicked()" class="btn btn-secondary">Choose Member Manually</button>

            </div>
            <div class="btn-group mr-2 mb-2" role="group" aria-label="Second group">
              <button type="button" onclick="automaticButtonClicked()" class="btn btn-secondary">Assign Task Automatically</button>

            </div>
        </div>

        <input type="hidden" id="is-automatic" name="is-automatic" value="false">

        <div class="form-group" id="choose-member">
            <label for="sel1">Select Member</label>
            <select class="form-control" name="member">
                <option disabled selected value> -- Select an Member-- </option>
                @foreach($members as $member)
                    @if(!$member->isLeader())
                      <option value="{{$member->id}}">{{$member->name}}</option>
                    @endif
                  @endforeach
            </select>
        </div>




        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
      flatpickr("#task-deadline", {
            enableTime: true,
            dateFormat: "Y-m-d H:i:s",


        });

        $chooseMemberSelect = document.getElementById('choose-member');
        $isAutomatic = document.getElementById('is-automatic');
        document.getElementById('chooseButton').click();

        function chooseButtonClicked()
        {
            console.log("jdbjd");
            $isAutomatic.value = "false";
            $chooseMemberSelect.classList.remove('d-none');
        }
        function automaticButtonClicked()
        {

            $isAutomatic.value = "true";
            $chooseMemberSelect.classList.add('d-none');
        }

</script>

@endsection

resources/views/task/edit.blade.php
@extends('layouts.app')
@section('page-title','Create Task')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection
@section('content')


<div class="row">
    <div class="mx-auto col-md-8">

    <form action="{{ route('task.update',$task) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Task Title</label>
              <input
                type="text"
                name="task-title"
                class="form-control"
                value="{{$task->title}}"
                disabled
                placeholder="title">
        </div>

        <div class="form-group">
            <label for="task-deadline">Task Deadline</label>
            <input type="date"
            class="form-control"
            name="task-deadline"
            placeholder="Click here to enter a deadline"
            id="task-deadline">

        </div>


        <div class="form-group">
            <label for="sel1">Select Severity</label>
            <select class="form-control" name="task-priority">
                {{-- <option disabled selected value> -- Select an Severity -- </option> --}}
                <option value=0 @if($task->priority === 0)  selected @endif>Medium</option>
                <option value=1 @if($task->priority === 1)  selected @endif>High</option>
                <option value=2 @if($task->priority === 2)  selected @endif>Highest</option>
            </select>
        </div>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2 mb-2" role="group" aria-label="First group">
              <button type="button" id="chooseButton" onclick="chooseButtonClicked()" class="btn btn-secondary">Choose Member Manually</button>

            </div>
            <div class="btn-group mr-2 mb-2" role="group" aria-label="Second group">
              <button type="button" onclick="automaticButtonClicked()" class="btn btn-secondary">Assign Task Automatically</button>

            </div>
        </div>

        <input type="hidden" id="is-automatic" name="is-automatic" value="false">

        <div class="form-group" id="choose-member">
            <label for="sel1">Select Member</label>
            <select class="form-control" name="task-member">
                <option disabled selected value> -- Select an Member-- </option>
                @foreach($members as $member)
                    @if(!$member->isLeader())
                      <option value="{{$member->id}}">{{$member->name}}</option>
                    @endif
                  @endforeach
            </select>
        </div>




        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    var taskDeadline = @json($task->deadline->toDateTimeString());

      flatpickr("#task-deadline", {
            enableTime: true,
            minDate: 'today',
            allowInput: true,
            dateFormat: "Y-m-d H:i:ss",
            defaultDate: taskDeadline,

        });

        $chooseMemberSelect = document.getElementById('choose-member');
        $isAutomatic = document.getElementById('is-automatic');
        document.getElementById('chooseButton').click();

        function chooseButtonClicked()
        {
            console.log("jdbjd");
            $isAutomatic.value = "false";
            $chooseMemberSelect.classList.remove('d-none');
        }
        function automaticButtonClicked()
        {

            $isAutomatic.value = "true";
            $chooseMemberSelect.classList.add('d-none');
        }

</script>

@endsection

resources/views/task/index.blade.php
@extends('layouts.app')



@section('content')


<ol class="breadcrumb mb-4  bg-primary">
    <li class="breadcrumb-item active text-white">Team Tasks</li>
</ol>

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Assigned To</th>
        <th scope="col">Status</th>
        <th scope="col">Priority</th>
        <th scope="col">Deadline</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    @foreach($tasks as $task)
      <tr>

        <td class="{{$task->statusColor()}}">{{$task->title}}</td>
        <td class="{{$task->statusColor()}}">{{$task->assignedTo()->name ??"NONE"}}</td>
        <td class="{{$task->statusColor()}}">{{$task->status}}</td>
        <td class="{{$task->statusColor()}}">{!!$task->priority!!}</td>
        <td class="{{$task->statusColor()}}"> @if($task->deadline < now()){{$task->deadline}}  @else{{ $task->deadline->diffForHumans(['parts' => 4])}} @endif </td>
        <td>
            <div class="d-flex">
                @if(auth()->user()->can('acceptOrReject',$task))

                <form id="accept_form" action="{{route('task.update',$task)}}" method="POST">
                    @csrf
                @method('PUT')
                    <input type="hidden" name="is_task_accept" value="true">
                    <input type="hidden" name="task_leader" value="{{auth()->id()}}">
                    <input type="hidden" id="input-points" name="task_points" value=1>


                </form>

                <button id="accept_button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal">Accept</button>
                <form action="{{route('task.update',$task)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <input type="hidden" name="is_task_reassign" value="true">
                    <button type="submit" class="btn btn-sm ml-2 btn-danger">Re-assign</button>
                </form>


                @elseif(auth()->user()->can('assign',$task))

                <a href="{{route('task.assign',$task)}}" class="btn btn-primary btn-sm">Assign</a>


                @else

                       <p class="{{$task->statusColor()}}">{{$task->status}}</p>
                @endcan


            </div>
        </td>

    @endforeach
    </tbody>
  </table>


  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Submit Ratings</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="container">
                <div id="rating-component"></div>
              </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button"  onclick='acceptButtonHandler()' class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


@endsection

@section('page-level-scripts')



<script>

        $isSelected = false;
        $selectedStar = 0;
        $ratingComponent = document.getElementById('rating-component');
        $ratingComponent.classList.add('d-flex','justify-content-center');
        for(i=0;i<3;i++)
        {
            $starContainer = document.createElement('div');
            $starContainer.classList.add('ml-3','star-container');
            //creating star
            $star = document.createElement('div');
            $starContainer.setAttribute('id',i+1);
            $star.classList.add('fa','fa-star','fa-2x');
            //adding to container
            $starContainer.appendChild($star);
            //registering the events to star-containers
            $starContainer.addEventListener("mouseenter",starEnterHandler.bind(null,i+1));
            $starContainer.addEventListener("mouseleave",starLeaveHandler);
            $starContainer.addEventListener("click",starClickedHandler);
            //appending the star container to main-component
            $ratingComponent.appendChild($starContainer);

        }
        function starEnterHandler($starContainerId)
        {

            $selectedStar = $starContainerId;
            if($isSelected)
            {
                //setting back the status
                $isSelected = false;
                document.querySelectorAll('.star-container').forEach($starContainer => {
                    $starContainer.addEventListener("mouseleave",starLeaveHandler);
                });
            }

            //removing colors from all stars
            for(i=1;i<=3;i++)
            {
                document.getElementById(i).classList.remove('text-warning');
                document.getElementById(i).classList.remove('text-success');
            }

            //default color
            $textColor = 'text-warning';
            //success color
            if($starContainerId === 3)
            $textColor = 'text-success';


            //adding colors to valid stars
            for(i=1;i<=$starContainerId;i++)
            {

                $star = document.getElementById(i);
                if(!$star.classList.contains('text-warning'))
                     $star.classList.add($textColor);
            }
        }

        function starLeaveHandler()
        {
            //removing colors from all stars
            for(i=1;i<=3;i++)
            {
                document.getElementById(i).classList.remove('text-warning');
                document.getElementById(i).classList.remove('text-success');
            }
        }

        function starClickedHandler()
        {
            //preserving the status for clicked
            $isSelected = true;

            //removing starLeave event to prevent the removing of colors
            document.querySelectorAll('.star-container').forEach($starContainer => {
            $starContainer.removeEventListener("mouseleave",starLeaveHandler);
            });


        }


</script>

<script>
    function acceptButtonHandler()
     {

        $form = document.getElementById('accept_form');
        $pointsInput = document.getElementById('input-points');
        $pointsInput.value = 1;
        if($isSelected)
        {
            $pointsInput.value = $selectedStar*3;
        }
        $form.submit();
     }


 </script>


@endsection