routes/web.php
<?php

use App\Http\Controllers\TasksController;
use Illuminate\Support\Facades\Route;
use App\Task;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin/welcome');
// });
// Route::get('/', function () {
//     return view
// }


Route::resource('team', 'TeamsController')->middleware('auth');
Route::resource('task', 'TasksController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');

Route::get('task/{task}/assign', 'TasksController@assign')->name('task.assign');
Auth::routes();
Route::get('task/show/{status}', 'TasksController@memberTasks')->name('task.membertasks');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', function () {

    // if (auth()->user()) {

    //     $user = auth()->user();
    //     if ($user->isLeader()) {
    //         $tasks = Task::where('team_id', $user->team_id)->get();
    //         return view('leaderDashboard')->with(['tasks' => $tasks]);
    //     }
    //     if ($user->isMember()) {
    //         $taskIds = DB::table('users_tasks')->where('user_id', 9)->pluck('task_id');
    //         $tasks = Task::whereIn('id', $taskIds)->get();
    //         return view('memberDashboard')->with(['tasks' => $tasks]);
    //     }
    // } else {
    //     return redirect(route('login'));
    // }
})->name('dashboard')->middleware('roleForDashboard');

resources/views/member/create.blade.php
@extends('layouts.app')
@section('page-title','Create Member')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection
@section('content')


<div class="row">
    <div class="mx-auto col-md-8">
        <div class="p-3">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>





</div>
    </div>
</div>
@endsection