routes/web.php
<?php

use App\Http\Controllers\TasksController;
use Illuminate\Support\Facades\Route;
use App\Task;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin/welcome');
// });
// Route::get('/', function () {
//     return view
// }


Route::resource('team', 'TeamsController')->middleware('auth');
Route::resource('task', 'TasksController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');

Route::get('task/{task}/assign', 'TasksController@assign')->name('task.assign');
Auth::routes();
Route::get('task/show/{status}', 'TasksController@memberTasks')->name('task.membertasks');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', function () {

    // if (auth()->user()) {

    //     $user = auth()->user();
    //     if ($user->isLeader()) {
    //         $tasks = Task::where('team_id', $user->team_id)->get();
    //         return view('leaderDashboard')->with(['tasks' => $tasks]);
    //     }
    //     if ($user->isMember()) {
    //         $taskIds = DB::table('users_tasks')->where('user_id', 9)->pluck('task_id');
    //         $tasks = Task::whereIn('id', $taskIds)->get();
    //         return view('memberDashboard')->with(['tasks' => $tasks]);
    //     }
    // } else {
    //     return redirect(route('login'));
    // }
})->name('dashboard')->middleware('roleForDashboard');

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{

    //relationship functions:

    public function leader()
    {
        return $this->hasOne(User::class, 'id', 'leader_id');
    }

    public function members()
    {

        return $this->hasMany(User::class)->where('role', 'team-member');
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
    public function actionTasks()
    {

        return $this->tasks()->whereIn('status', ['review', 'created'])->get();
    }
    public function bestMember()
    {
        $member =  User::where('team_id', $this->id)->where('role', 'team-member')->where('points', '>', 0)->orderByDesc('points')->first();

        if ($member) {
            return $member->name;
        } else {
            return 'Not Available';
        }
    }
}

app/Http/Controllers/TeamsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Team;
use App\User;

class TeamsController extends Controller
{
    //
    public function index()
    {

        $this->authorize('index', Team::class);
        $teams = Team::all();
        return view('team.index')->with(['teams' => $teams]);
    }

    public function create()
    {

        $this->authorize('create', Team::class);
        $users = User::whereNull('team_id')->get();

        return view('team.create')->with(['users' => $users]);
    }

    public function store()
    {

        $this->authorize('create', Team::class);
        $team = new Team();
        $team->name = request('team-name');
        $leader = User::where('id', request('team-leader'))->first();
        $leader->password = Hash::make('luvmylife');
        $leader->status = "vacant";
        $leader->role = "team-leader";
        $team->leader_id = $leader->id;
        $team->save();

        $members = request('team-members');
        for ($i = 0; $i < count($members); $i++) {
            $member = User::where('id', $members[$i])->first();
            $team->members()->save($member);
        }
        $leader->team_id = $team->id;
        $leader->Save();
        return redirect(route('team.index'));
    }

    public function show(Team $team)
    {
        $this->authorize('view', $team);
        return view('team.show')->with(['team' => $team]);
    }
    public function edit(Team $team)
    {
        $users = User::whereNull('team_id')->orWhere('team_id', $team->id)->get();
        return view('team.edit')->with(['team' => $team, 'users' => $users]);
    }
    public function update(Request $request, $oldTeamId)
    {


        $oldTeam = Team::findOrFail($oldTeamId);
        $oldMembers =  $oldTeam->members;
        $newMembers = request('team-members');

        //removing all the old members

        for ($i = 0; $i < count($oldMembers); $i++) {
            $oldMembers[$i]->team_id = null;
            $oldMembers[$i]->role = 'team-member';
            $oldMembers[$i]->save();
        }



        //adding new members:
        for ($i = 0; $i < count($newMembers); $i++) {
            $newMember = User::findOrFail($newMembers[$i]);
            $oldTeam->members()->save($newMember);
        }




        //adding Leader of team

        $oldTeam->leader_id = null;
        $teamLeader = User::findOrFail(request('team-leader'));
        $teamLeader->role = "team-leader";
        $teamLeader->team_id = $oldTeam->id;
        $teamLeader->save();
        $oldTeam->leader_id = $teamLeader->id;




        //updating the name:
        $oldTeam->name = request('name');

        //saving the team
        $oldTeam->save();

        return redirect(route('team.index'));
    }
}

resources/views/team/create.blade.php
@extends('layouts.app')
@section('page-title','Create Team')
@section('content')
<div class="row">
    <div class="mx-auto col-md-8">
    <form action="{{ route('team.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Team Name</label>
              <input type="text" name="team-name" class="form-control"  placeholder="name">
        </div>

        <div class="form-group">
            <label for="sel1">Select Leader</label>
            <select class="form-control" onchange = "renderMembers(this.value,{{$users}})" name="team-leader">
                <option disabled selected value> -- select an leader -- </option>
                @foreach($users as $user)
             <option value="{{$user->id}}">{{$user->name}}</option>
              @endforeach
            </select>
          </div>

          <div class="form-group">
            <label for="sel2">Select Leader</label>
            <select id="sel2" class="form-control" name="team-members[]" multiple>
              @foreach($users as $user)

                 <option value="{{$user->id}}">{{$user->name}}</option>
              @endforeach
            </select>
          </div>


        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script>

    function renderMembers($leaderId,$users)
    {
        $membersSelect = document.getElementById('sel2');
        $membersSelect.innerHTML = "";
        $users.forEach($user => {
            if($leaderId != $user.id){
            $userOption = document.createElement('option');
            $userOption.setAttribute('value',$user.id);
            $userOption.innerHTML = $user.name;
            $membersSelect.appendChild($userOption);
            }
        });

    }
</script>
@endsection

resources/views/team/edit.blade.php
@extends('layouts.app')
@section('page-title','Update Team')
@section('content')
<div class="row">
    <div class="mx-auto col-md-8">
    <form action="{{ route('team.update',$team) }}" method="POST">
        @method('PUT')
        @csrf

        <div class="form-group">
            <label for="name">Group Name</label>

        <input type="text" name="name" value="{{$team->name}}" class="form-control" >

        </div>


        <div class="form-group">
            <label for="sel1">Select Leader</label>
            <select class="form-control" onchange = "renderMembers(this.value,{{$users}},{{$team}})" name="team-leader">
            <option selected value="{{$team->leader->id}}">{{$team->leader->name}}</option>
                @foreach($users as $user)
              @if(!$user->team_id)
             <option value="{{$user->id}}">{{$user->name}}</option>
            @endif
             @endforeach
            </select>
          </div>


          <div class="form-group">
            <label for="sel2">Select Leader</label>
            <select id="sel2" class="form-control" name="team-members[]" multiple>
              @foreach($users as $user)
                @if($team->leader->id !== $user->id)
                 <option @if($user->team_id === $team->id)selected @endif value="{{$user->id}}">{{$user->name}}</option>
                @endif
                 @endforeach
            </select>
          </div>



        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script>

    function renderMembers($leaderId,$users,$team)
    {
        $membersSelect = document.getElementById('sel2');
        $membersSelect.innerHTML = "";
        $users.forEach($user => {
            if($leaderId != $user.id){

            console.log($leaderId);
            $userOption = document.createElement('option');
            $userOption.setAttribute('value',$user.id);
            $userOption.innerHTML = $user.name;
            if($user.team_id === $team.id && $user.id !== $team.leader_id)
            {
                $userOption.setAttribute('selected','true');
            }
            $membersSelect.appendChild($userOption);
            }
        });

    }
</script>
@endsection

resources/views/team/index.blade.php
@extends('layouts.app')
@section('page-title','Teams')
@section('content')

<div class="d-flex justify-content-end mb-3">
    <a class="btn btn-primary" href="{{route('team.create')}}">Add Team</a>
</div>
<table class="table table-bordered">
    <thead>
      <tr>

        <th scope="col">Name</th>
        <th scope="col">Leader</th>
        <th scope="col">Tasks</th>
        <th scope="col">Members</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    @foreach($teams as $team)
      <tr>

        <td>{{$team->name}}</td>
        <td>{{$team->leader->name}}</td>
        <td>{{$team->tasks()->count()}}</td>
        <td>{{$team->members()->count()}}</td>
        <td>
            <a href="{{route('team.show',$team->id)}}" class="btn btn-primary">View</a>
            <a href="{{route('team.edit',$team->id)}}" class="btn btn-primary">Edit</a></td>
      </tr>
    @endforeach
    </tbody>
  </table>
@endsection

resources/views/team/show.blade.php
@extends('layouts.app')
@section('page-title','Team Details')
@section('content')
<h1>Tasks</h1>
<div class="row">
    <div class="col-md-8">
        <table class="table table-bordered">
            <thead>
              <tr>

                <th scope="col">Task</th>
                <th scope="col">Priority</th>
                <th scope="col">Deadline</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
            @foreach($team->tasks as $task)
              <tr>

                <td>{{$task->title}}</td>
                <td>{{$task->priority}}</td>
                <td>{{$task->deadline}}</td>
                <td>{{$task->status}}</td>

              </tr>
            @endforeach
            </tbody>
          </table>

    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="d-flex justify-content-between">
            <h1>Members</h1>

        </div>
        <table class="table table-bordered">
            <thead>
              <tr>

                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Status</th>
                <th scope="col">Role</th>

              </tr>
            </thead>
            <tbody>
            @foreach($team->members as $member)
              <tr>

                <td>{{$member->name}}</td>
                <td>{{$member->email}}</td>
                <td>{{$member->status}}</td>
                 <td>{{$member->role}}</td>




              </tr>
            @endforeach
            </tbody>
          </table>

    </div>
</div>

@endsection