routes/web.php
<?php

use App\Http\Controllers\TasksController;
use Illuminate\Support\Facades\Route;
use App\Task;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin/welcome');
// });
// Route::get('/', function () {
//     return view
// }


Route::resource('team', 'TeamsController')->middleware('auth');
Route::resource('task', 'TasksController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');

Route::get('task/{task}/assign', 'TasksController@assign')->name('task.assign');
Auth::routes();
Route::get('task/show/{status}', 'TasksController@memberTasks')->name('task.membertasks');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', function () {

    // if (auth()->user()) {

    //     $user = auth()->user();
    //     if ($user->isLeader()) {
    //         $tasks = Task::where('team_id', $user->team_id)->get();
    //         return view('leaderDashboard')->with(['tasks' => $tasks]);
    //     }
    //     if ($user->isMember()) {
    //         $taskIds = DB::table('users_tasks')->where('user_id', 9)->pluck('task_id');
    //         $tasks = Task::whereIn('id', $taskIds)->get();
    //         return view('memberDashboard')->with(['tasks' => $tasks]);
    //     }
    // } else {
    //     return redirect(route('login'));
    // }
})->name('dashboard')->middleware('roleForDashboard');

resources/views/layouts/_footer.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2020</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/_header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }}</title>



<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->

<link href="{{asset('assets/css/styles.css')}}" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
    crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
    crossorigin="anonymous"></script>

@yield('page-level-styles')

resources/views/layouts/_navigation.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="index.html">Start Bootstrap</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search"
                aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <button type="submit" class="dropdown-item">Logout</button>
                  </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/_scripts.blade.php
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src ="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>

<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{{-- custom js --}}
<script src="{{asset('assets/js/scripts.js')}}"></script>
<script> </script>


    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{{asset('assets/assets/demo/chart-area-demo.js')}}"></script>
    <script src="{{asset('assets/assets/demo/chart-bar-demo.js')}}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{{asset('assets/assets/demo/datatables-demo.js')}}"></script> --}}
    @yield('page-level-scripts')

resources/views/layouts/_sidebar.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{route('dashboard')}}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>

                <div class="sb-sidenav-menu-heading">Admin</div>

                @auth
                {{-- Teams --}}


                @php
                    $userRole = auth()->user()->role;
                @endphp

                @if($userRole === 'team-leader')
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#teamOption"
                    aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Team
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                     </a>

                     <div class="collapse" id="teamOption" aria-labelledby="headingOne"
                     data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                           <a class="nav-link" href="{{route('team.show',auth()->user()->team_id)}}">View Team</a>
                        </nav>
                    </div>
                    <div class="collapse" id="teamOption" aria-labelledby="headingOne"
                    data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{route('team.edit',auth()->user()->team_id)}}">Edit Team</a>

                    </nav>
                </div>


                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#taskOption"
                aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Tasks
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                 </a>

                 <div class="collapse" id="taskOption" aria-labelledby="headingOne"
                 data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                       <a class="nav-link" href="{{route('task.index')}}">View Tasks</a>
                    </nav>
                </div>

                @endif


                @if(auth()->user()->role === 'admin')
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Teams
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                    data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{route('team.index')}}">All Teams</a>
                    </nav>
                </div>
                @endif



                @if(auth()->user()->role === 'team-member')
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#memberTaskOptions"
                aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                     Tasks
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="memberTaskOptions" aria-labelledby="headingOne"
                    data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{route('task.index')}}">All Tasks</a>
                    </nav>
                </div>
                @endif



                @endauth
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            Start Bootstrap
        </div>
    </nav>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    @include('layouts._header')
    @yield('page-level-styles')
</head>
<body class="sb-nav-fixed">
    @include('layouts._navigation')
    <div id="layoutSidenav">
       @include('layouts._sidebar')
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">


                       @yield('page-header')

                 @yield('content')

                </div>
            </main>
           @include('layouts._footer')
        </div>
    </div>

    @include('layouts._scripts');

</body>
</html>